package org.vicomtech.opener.bratAdaptionTools;

import java.util.List;
import java.util.Map;

import com.google.common.collect.Lists;
import com.google.common.collect.Maps;

public class BratAnnotationsManager {

	public static enum AnnotationIdType {
		ENTITY("T"), RELATION("R"), ATTRIBUTE("A"), EVENT("E"), NORMALIZATION(
				"N"), NOTE("#"), EQUIVALENCE("*");
		private String letter;
		private AnnotationIdType(String letter) {
			this.letter = letter;
		}
		@Override
				public String toString() {
					return letter;
				}
	}
	
	private Map<AnnotationIdType,Integer>annotationIdCount;
	private List<BratAnnotation>bratAnnotations;
	
	
	public BratAnnotationsManager() {
		annotationIdCount=Maps.newHashMap();
		for(AnnotationIdType annotationIdType:AnnotationIdType.values()){
			annotationIdCount.put(annotationIdType, 1);
		}
		bratAnnotations=Lists.newArrayList();
	}

	/**
	 * This method adds annotations taking care of the incremental ID for each
	 * type of annotation. DO NOT MIX with addParsedAnnotation method, because
	 * ID conflicts will probably happen
	 * 
	 * @param annotationIdType
	 * @param type
	 * @param start
	 * @param end
	 * @param involvedEntities
	 * @param text
	 */
	public void addAnnotation(AnnotationIdType annotationIdType, String type,
			int start, int end, List<String> involvedEntities, String text) {
		BratAnnotation bratAnnotation=new BratAnnotation();
		int idNum=getAnnotationIdAndUpdate(annotationIdType);
		bratAnnotation.setId(composedAnnotationId(annotationIdType, idNum));
		bratAnnotation.setType(type);
		bratAnnotation.setOffsets(start, end);
		bratAnnotation.setText(text);
		bratAnnotation.setInvolvedEntities(involvedEntities);
		bratAnnotations.add(bratAnnotation);
	}
	
	/**
	 * Careful, this is fo adding existing parsed brat annotations (as they are
	 * generated by Brat). So no ID checking is performed for now. It must not
	 * be used at the same time than "addAnnotation" method, because that method
	 * is to add artifical annotations (i.e. not generated by Brat)
	 * 
	 * @param bratAnnotation
	 */
	public void addParsedAnnotation(BratAnnotation bratAnnotation){
		bratAnnotations.add(bratAnnotation);
	}
	
	protected int getAnnotationIdAndUpdate(AnnotationIdType annotationIdType){
		Integer count=annotationIdCount.get(annotationIdType);
		annotationIdCount.put(annotationIdType, (count+1));
		return count;
	}
	
	protected String composedAnnotationId(AnnotationIdType annotationIdType,int number){
		if(annotationIdType==AnnotationIdType.EQUIVALENCE){
			return "*";
		}else{
			return annotationIdType.toString()+number;
		}
	}
	
	public List<BratAnnotation> getAnnotations(){
		return bratAnnotations;
	}
	
}
