/* Generated by javafromjson */
package org.vicomtech.opener.annotationReviews;

public class Hotel {
	private java.lang.String city;

 	public void setCity(java.lang.String city) {
		this.city = city;
	}

	public java.lang.String getCity() {
		return city;
	}

	private java.lang.String country;

 	public void setCountry(java.lang.String country) {
		this.country = country;
	}

	public java.lang.String getCountry() {
		return country;
	}

	private java.lang.String tags;

 	public void setTags(java.lang.String tags) {
		this.tags = tags;
	}

	public java.lang.String getTags() {
		return tags;
	}

	private java.lang.String name;

 	public void setName(java.lang.String name) {
		this.name = name;
	}

	public java.lang.String getName() {
		return name;
	}

}