/* Generated by javafromjson */
package org.vicomtech.opener.annotationReviews;

public class Ratings {
	private java.lang.Integer service;

 	public void setService(java.lang.Integer service) {
		this.service = service;
	}

	public java.lang.Integer getService() {
		return service;
	}

	private java.lang.Integer value;

 	public void setValue(java.lang.Integer value) {
		this.value = value;
	}

	public java.lang.Integer getValue() {
		return value;
	}

	private java.lang.Integer overall;

 	public void setOverall(java.lang.Integer overall) {
		this.overall = overall;
	}

	public java.lang.Integer getOverall() {
		return overall;
	}

	private java.lang.Integer rooms;

 	public void setRooms(java.lang.Integer rooms) {
		this.rooms = rooms;
	}

	public java.lang.Integer getRooms() {
		return rooms;
	}

	private java.lang.Integer location;

 	public void setLocation(java.lang.Integer location) {
		this.location = location;
	}

	public java.lang.Integer getLocation() {
		return location;
	}

	private java.lang.Integer food;

 	public void setFood(java.lang.Integer food) {
		this.food = food;
	}

	public java.lang.Integer getFood() {
		return food;
	}

}