/* Generated by javafromjson */
package org.vicomtech.opener.annotationReviews;

public class ReviewForAnnotation {
	private _id _id;

 	public void set_id(_id _id) {
		this._id = _id;
	}

	public _id get_id() {
		return _id;
	}

	private java.lang.Object visit_reason;

 	public void setVisit_reason(java.lang.Object visit_reason) {
		this.visit_reason = visit_reason;
	}

	public java.lang.Object getVisit_reason() {
		return visit_reason;
	}

	private java.lang.String id_on_review_site;

 	public void setId_on_review_site(java.lang.String id_on_review_site) {
		this.id_on_review_site = id_on_review_site;
	}

	public java.lang.String getId_on_review_site() {
		return id_on_review_site;
	}

	private java.lang.Object recommend;

 	public void setRecommend(java.lang.Object recommend) {
		this.recommend = recommend;
	}

	public java.lang.Object getRecommend() {
		return recommend;
	}

	private java.lang.Object url;

 	public void setUrl(java.lang.Object url) {
		this.url = url;
	}

	public java.lang.Object getUrl() {
		return url;
	}

	private java.lang.Integer hotel_id;

 	public void setHotel_id(java.lang.Integer hotel_id) {
		this.hotel_id = hotel_id;
	}

	public java.lang.Integer getHotel_id() {
		return hotel_id;
	}

	private Hotel hotel;

 	public void setHotel(Hotel hotel) {
		this.hotel = hotel;
	}

	public Hotel getHotel() {
		return hotel;
	}

	private java.lang.String language;

 	public void setLanguage(java.lang.String language) {
		this.language = language;
	}

	public java.lang.String getLanguage() {
		return language;
	}

	private java.lang.Object stars;

 	public void setStars(java.lang.Object stars) {
		this.stars = stars;
	}

	public java.lang.Object getStars() {
		return stars;
	}

	private java.lang.String source_name;

 	public void setSource_name(java.lang.String source_name) {
		this.source_name = source_name;
	}

	public java.lang.String getSource_name() {
		return source_name;
	}

	private java.lang.String comment;

 	public void setComment(java.lang.String comment) {
		this.comment = comment;
	}

	public java.lang.String getComment() {
		return comment;
	}

	private java.lang.Integer connection_id;

 	public void setConnection_id(java.lang.Integer connection_id) {
		this.connection_id = connection_id;
	}

	public java.lang.Integer getConnection_id() {
		return connection_id;
	}

	private java.lang.Object visit_date;

 	public void setVisit_date(java.lang.Object visit_date) {
		this.visit_date = visit_date;
	}

	public java.lang.Object getVisit_date() {
		return visit_date;
	}

	private Ratings ratings;

 	public void setRatings(Ratings ratings) {
		this.ratings = ratings;
	}

	public Ratings getRatings() {
		return ratings;
	}

	private Reviewer reviewer;

 	public void setReviewer(Reviewer reviewer) {
		this.reviewer = reviewer;
	}

	public Reviewer getReviewer() {
		return reviewer;
	}

	private java.lang.String review_date;

 	public void setReview_date(java.lang.String review_date) {
		this.review_date = review_date;
	}

	public java.lang.String getReview_date() {
		return review_date;
	}

	private java.lang.String title;

 	public void setTitle(java.lang.String title) {
		this.title = title;
	}

	public java.lang.String getTitle() {
		return title;
	}

	private java.lang.Object age_group;

 	public void setAge_group(java.lang.Object age_group) {
		this.age_group = age_group;
	}

	public java.lang.Object getAge_group() {
		return age_group;
	}

	private java.lang.String review_id;

 	public void setReview_id(java.lang.String review_id) {
		this.review_id = review_id;
	}

	public java.lang.String getReview_id() {
		return review_id;
	}

	private java.lang.Integer word_count;

 	public void setWord_count(java.lang.Integer word_count) {
		this.word_count = word_count;
	}

	public java.lang.Integer getWord_count() {
		return word_count;
	}

	private java.lang.String connection_url;

 	public void setConnection_url(java.lang.String connection_url) {
		this.connection_url = connection_url;
	}

	public java.lang.String getConnection_url() {
		return connection_url;
	}

}