/* Generated by javafromjson */
package org.vicomtech.opener.annotationReviews;

public class Reviewer {
	private java.lang.String url;

 	public void setUrl(java.lang.String url) {
		this.url = url;
	}

	public java.lang.String getUrl() {
		return url;
	}

	private java.lang.String location;

 	public void setLocation(java.lang.String location) {
		this.location = location;
	}

	public java.lang.String getLocation() {
		return location;
	}

	private java.lang.String _id;

 	public void set_id(java.lang.String _id) {
		this._id = _id;
	}

	public java.lang.String get_id() {
		return _id;
	}

	private java.lang.String company;

 	public void setCompany(java.lang.String company) {
		this.company = company;
	}

	public java.lang.String getCompany() {
		return company;
	}

	private java.lang.String name;

 	public void setName(java.lang.String name) {
		this.name = name;
	}

	public java.lang.String getName() {
		return name;
	}

	private java.lang.Integer age;

 	public void setAge(java.lang.Integer age) {
		this.age = age;
	}

	public java.lang.Integer getAge() {
		return age;
	}

}